# This is a basic workflow to help you get started with Actions

name: fkmobiles

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#    - uses: actions/checkout@v2
    - uses: actions/checkout@v4

    # Runs a single command using the runners shell
    - name: Installing Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: GitHub Action for Yarn
    # You may pin to the exact commit or the version.
    # uses: Borales/actions-yarn@3766bb1335b98fb13c60eaf358fe20811b730a88
      uses: Borales/actions-yarn@v5.0.0
      with:
    # Yarn command
        cmd: install  #npm install # yarn build # npm run build
    - name: Creating build
      run: npm run build #yarn build
       #run: yarn build


    # Runs a set of commands using the runners shell
    - name: Installing surge
      run: npm install --global surge
    - name: Deploying using surge
      run: surge ./ fkmobiles.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
